# Generated by Django 2.1.5 on 2019-08-27 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_car_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='pic',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
